// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewsihvtqrnkvkxrllalv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c2lodnRxcm5rdmt4cmxsYWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTU0MzAsImV4cCI6MjA2MDU5MTQzMH0.WyQrhvg8XgFXek8OIeYf_9bXroM1BNyfm0FnA0MGPX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);